export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

import '../styles/globals.scss';

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
