name: Staging deployment
on:
  push:
    branches: [staging]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MACHINE_PRIVATE_KEY }}
          known_hosts: 'undetermined-yet'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.MACHINE_HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Add environment variables
        run: |
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_RECAPTCHA_V3_PK=${{ secrets.NEXT_PUBLIC_RECAPTCHA_V3_PK }}" >> .env.local
          echo "RECAPTCHA_V3_SK=${{secrets.RECAPTCHA_V3_SK}}" >> .env.local
          echo "COINMARKETCAP_API_KEY=${{secrets.COINMARKETCAP_API_KEY}}" >> .env.local
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}" >> .env.local
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY_TEST=${{secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY_TEST}}" >> .env.local
          echo "STRIPE_PRIVATE_KEY=${{secrets.STRIPE_PRIVATE_KEY}}" >> .env.local
          echo "STRIPE_PRIVATE_KEY_TEST=${{secrets.STRIPE_PRIVATE_KEY_TEST}}" >> .env.local
          echo "JWT_DRIVE_SERVER=${{secrets.JWT_DRIVE_SERVER}}" >> .env.local
          echo "NEXT_DRIVE_API_URL=${{secrets.NEXT_DRIVE_API_URL}}" >> .env.local
          echo "NEXT_PUBLIC_SEGMENT_KEY=${{secrets.NEXT_PUBLIC_SEGMENT_KEY}}" >> .env.local
          echo "NEXT_PUBLIC_SEGMENT_KEY_TEST=${{secrets.NEXT_PUBLIC_SEGMENT_KEY_TEST}}" >> .env.local
          echo "NEXT_PUBLIC_DRIVE_WEB=${{secrets.NEXT_PUBLIC_DRIVE_WEB}}" >> .env.local
          echo "SECRET_AUTH=${{secrets.SECRET_AUTH}}" >> .env.local
          echo "SEGMENT_API_KEY_PROD=${{secrets.SEGMENT_API_KEY_PROD}}" >> .env.local
          echo "NEXT_DRIVE_WEB=${{secrets.NEXT_DRIVE_WEB}}" >> .env.local
          echo "NEXT_BRIDGE_GATEWAY_USERNAME=${{secrets.NEXT_BRIDGE_GATEWAY_USERNAME}}" >> .env.local
          echo "NEXT_BRIDGE_GATEWAY_PASS=${{secrets.NEXT_BRIDGE_GATEWAY_PASS}}" >> .env.local
          echo "NEXT_BRIDGE_URL=${{secrets.NEXT_BRIDGE_URL}}" >> .env.local
          echo "NEXT_STORAGE_API_URL=${{secrets.NEXT_STORAGE_API_URL}}" >> .env.local
          echo "NEXT_PUBLIC_COUNTRY_API_URL=${{secrets.NEXT_PUBLIC_COUNTRY_API_URL}}" >> .env.local
          echo "DRIVE_API_URL=${{secrets.DRIVE_API_URL}}" >> .env.local
          echo "DRIVE_WEB=${{secrets.DRIVE_WEB}}" >> .env.local
          echo "NEXT_PUBLIC_TEMP_MAIL_URL=${{secrets.NEXT_PUBLIC_TEMP_MAIL_URL}}" >> .env.local
          echo "NEXT_PUBLIC_IOS_APP_ID=${{secrets.NEXT_PUBLIC_IOS_APP_ID}}" >> .env.local
          echo "NEXT_PUBLIC_PAYMENTS_API=${{secrets.NEXT_PUBLIC_PAYMENTS_API}}" >> .env.local
          echo "MAILERLITE_API=${{secrets.MAILERLITE_API}}" >> .env.local
          echo "MAILERLITE_API_KEY=${{secrets.MAILERLITE_API_KEY}}" >> .env.local
          echo "COUPON_SUBSCRIPTION_90_OFF=${{secrets.COUPON_SUBSCRIPTION_90_OFF}}" >> .env.local
          echo "COUPON_LIFETIME_GENERAL=${{secrets.COUPON_LIFETIME_GENERAL}}" >> .env.local
          echo "COUPON_LIFETIME_SPECIAL=${{secrets.COUPON_LIFETIME_SPECIAL}}" >> .env.local
          echo "COUPON_CLOUDWARDS=${{secrets.COUPON_CLOUDWARDS}}" >> .env.local
          echo "COUPON_SUBSCRIPTION_75_OFF=${{secrets.COUPON_SUBSCRIPTION_75_OFF}}" >> .env.local
          echo "COUPON_SPECIAL15=${{secrets.COUPON_SPECIAL15}}" >> .env.local
          echo "CURRENCY_VALUE=${{secrets.CURRENCY_VALUE}}" >> .env.local
          echo "BANANACRUMBS_ID=${{secrets.BANANACRUMBS_ID}}" >> .env.local
          echo "BANANACRUMBS_MFA=${{secrets.BANANACRUMBS_MFA}}" >> .env.local
          echo "ANNUAL_PLAN_80_DISCOUNT=${{secrets.ANNUAL_PLAN_80_DISCOUNT}}" >> .env.local
          echo "NEXT_PUBLIC_GA_ID=${{secrets.NEXT_PUBLIC_GA_ID}}" >> .env.local
          echo "NEXT_PUBLIC_IMPACT_API=${{secrets.NEXT_PUBLIC_IMPACT_API}}" >> .env.local
          echo "NEXT_PUBLIC_MATOMO_URL=${{secrets.NEXT_PUBLIC_MATOMO_URL}}" >> .env.local
          echo "COUPON_BLACK_FRIDAY_2023=${{secrets.COUPON_BLACK_FRIDAY_2023}}" >> .env.local
          echo "COUPON_CHRISTMAS=${{secrets.COUPON_CHRISTMAS}}" >> .env.local

      - name: Run Deploy Script
        run: "ssh -t ${{ secrets.MACHINE_USER }}@${{ secrets.MACHINE_HOSTNAME }} './deploy.sh'"
